// Generated by dojo-bindgen on Sun, 24 Nov 2024 19:07:25 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;

// Type definition for `depths_of_dread::models::Obstacle` struct
[Serializable]
public struct Obstacle {
    public ObstacleType obstacle_type;
    public Vec2 position;
}

// Type definition for `depths_of_dread::models::ObstacleType` enum
public abstract record ObstacleType() : Enum {
    public record RangeTrap() : ObstacleType;
    public record MeleeEnemy() : ObstacleType;
    public record NoTile() : ObstacleType;
    public record FireTrap() : ObstacleType;
    public record PoisonTrap() : ObstacleType;
}


// Model definition for `depths_of_dread::models::GameObstacles` model
public class depths_of_dread_GameObstacles : ModelInstance {
    [ModelField("game_id")]
        public uint game_id;

        [ModelField("instances")]
        public Obstacle[] instances;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        