// Generated by dojo-bindgen on Sun, 24 Nov 2024 19:07:25 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;

// Type definition for `depths_of_dread::models::PowerUp` struct
[Serializable]
public struct PowerUp {
    public PowerUpType power_type;
    public FieldElement powerup_felt;
}

// Type definition for `depths_of_dread::models::PowerUpType` enum
public abstract record PowerUpType() : Enum {
    public record Shield() : PowerUpType;
    public record Sword() : PowerUpType;
    public record FireDefense() : PowerUpType;
    public record PoisonDefense() : PowerUpType;
    public record None() : PowerUpType;
    public record Wings() : PowerUpType;
}


// Model definition for `depths_of_dread::models::PlayerPowerUps` model
public class depths_of_dread_PlayerPowerUps : ModelInstance {
    [ModelField("player")]
        public FieldElement player;

        [ModelField("powers")]
        public PowerUp[] powers;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        