// Generated by dojo-bindgen on Sun, 24 Nov 2024 19:07:25 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;

// Model definition for `depths_of_dread::models::GameCoins` model
public class depths_of_dread_GameCoins : ModelInstance {
    [ModelField("game_id")]
        public uint game_id;

        [ModelField("coins")]
        public Vec2[] coins;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        