// Generated by dojo-bindgen on Sun, 24 Nov 2024 19:07:25 +0000. Do not modify this file manually.
using Dojo;
using Dojo.Starknet;
using UnityEngine;
using TMPro;
using static EncodingService;


// Model definition for `depths_of_dread::models::PlayerData` model
public class depths_of_dread_PlayerData : ModelInstance {
    [ModelField("player")]
    public FieldElement player;

    [ModelField("username")]
    public FieldElement username;
    private string usernameDisplay;
    private TMP_Text usernameText;

    // Start is called before the first frame update
    void Start() {
        // usernameDisplay = username.Hex();
        // usernameText = GameObject.FindGameObjectWithTag("UsernameText").GetComponent<TMP_Text>();
        // usernameText.text = HexToASCII(usernameDisplay);
    }

    // Update is called once per frame
    void Update() {
        // if (username.Hex() != usernameDisplay)
        // {
        //     usernameDisplay = username.Hex();
        //     usernameText.text = HexToASCII(usernameDisplay);
        // }
    }
}

        